export const SERVICE_NAMES: Record<string, string> = {
  // VirtualSMS service_id values
  tg:  'Telegram',
  wa:  'WhatsApp',
  ig:  'Instagram',
  fb:  'Facebook',
  lf:  'TikTok',
  go:  'Google',
  tw:  'Twitter / X',
  ds:  'Discord',
  mm:  'Microsoft',
  am:  'Amazon',
  nf:  'Netflix',
  alj: 'Spotify',
  ub:  'Uber',
  ts:  'PayPal',
  tn:  'LinkedIn',
  fu:  'Snapchat',
  hb:  'Twitch',
  mt:  'Steam',
  // Legacy full-word slugs (orders placed before the slug migration)
  telegram:  'Telegram',
  whatsapp:  'WhatsApp',
  instagram: 'Instagram',
  facebook:  'Facebook',
  tiktok:    'TikTok',
  google:    'Google',
  twitter:   'Twitter / X',
  discord:   'Discord',
  microsoft: 'Microsoft',
  amazon:    'Amazon',
  netflix:   'Netflix',
  spotify:   'Spotify',
  uber:      'Uber',
  paypal:    'PayPal',
  linkedin:  'LinkedIn',
  snapchat:  'Snapchat',
  twitch:    'Twitch',
  steam:     'Steam',
  apple:     'Apple',
  binance:   'Binance',
  coinbase:  'Coinbase',
  viber:     'Viber',
  line:      'LINE',
}

export function displayService(slug: string): string {
  return SERVICE_NAMES[slug.toLowerCase()] ?? slug.charAt(0).toUpperCase() + slug.slice(1)
}
